name: Publish Website

#permissions:
#  content: write

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        working-directory: ./pages
        run: npm install --force
      - name: Build website
        working-directory: ./pages
        run: npm run build
      - name: Move website to publish dir
        working-directory: ./pages
        run: mv ./build ../docs
